name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_ID: docker.pkg.github.com/${{ github.repository }}/poker-du-jeudi:latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.PASSPHRASE }}
        key: ${{ secrets.SSH_KEY }}
        envs: DATABASE_URL,DATABASE_USERNAME,DATABASE_PASSWORD,GITHUB_TOKEN,GITHUB_ACTOR
        script: |
          echo "$GITHUB_TOKEN" | sudo docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
          sudo rm -rf /data/poker-du-jeudi
          sudo mkdir -p /data/poker-du-jeudi
          sudo chown deploy:deploy /data/poker-du-jeudi
          cd /data/poker-du-jeudi
          sudo git clone https://github.com/${{ github.repository }}.git
          sudo cd poker-du-jeudi-spring
          sudo echo DATABASE_URL=$DATABASE_URL >> .env
          sudo echo DATABASE_USERNAME=$DATABASE_USERNAME >> .env
          sudo echo DATABASE_PASSWORD=$DATABASE_PASSWORD >> .env
          sudo docker-compose down
          sudo docker-compose up -d
