name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_ID: docker.pkg.github.com/${{ github.repository }}/poker-du-jeudi:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker build . --file Dockerfile --tag $IMAGE_ID

      - name: Push the image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker push $IMAGE_ID

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.PASSPHRASE }}
        key: ${{ secrets.SSH_KEY }}
        envs: DATABASE_URL,DATABASE_USERNAME,DATABASE_PASSWORD,GITHUB_TOKEN,GITHUB_ACTOR,IMAGE_ID
        script: |
          echo "$GITHUB_TOKEN" | sudo docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
          sudo docker pull $IMAGE_ID
          sudo rm -rf /data/poker-du-jeudi
          sudo mkdir -p /data/poker-du-jeudi
          sudo chown deploy:deploy /data/poker-du-jeudi
          cd /data/poker-du-jeudi
          git clone https://github.com/${{ github.repository }}.git
          cd poker-du-jeudi-spring
          echo DATABASE_URL=$DATABASE_URL >> .env
          echo DATABASE_USERNAME=$DATABASE_USERNAME >> .env
          echo DATABASE_PASSWORD=$DATABASE_PASSWORD >> .env
          sudo docker-compose down
          sudo docker-compose up -d
