name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_ID: docker.pkg.github.com/${{ github.repository }}/poker-du-jeudi:latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        ENV_CONFIG: "blablabla"
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.PASSPHRASE }}
        key: ${{ secrets.SSH_KEY }}
        envs: ENV_CONFIG
        script: |
          sudo rm -rf /data/poker-du-jeudi
          sudo mkdir -p /data/poker-du-jeudi
          sudo chown deploy:deploy /data/poker-du-jeudi
          cd /data/poker-du-jeudi
          git clone https://github.com/${{ github.repository }}.git
          cd poker-du-jeudi-spring
          echo \"$ENV_CONFIG\" >> .env
          sudo docker-compose down
          sudo docker-compose up -d
